In [1]:
import pandas as pd
import numpy as np

In [2]:
data= pd.read_csv('Data.csv')
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [3]:
X= data.iloc[:,:-1].values

In [4]:
y= data.iloc[:,3].values

In [5]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [6]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN',strategy='median',axis=0)

In [7]:
imputer= imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [8]:
# Now we shall label encode the categorical column Country but as We want them to have equal weightage we will give them 
# dummy variables. We can use 'get_dummies' but we have to merge it then with actual dataframe, but not here.
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
X[:,0] = labelencoder_x.fit_transform(X[:,0])

In [9]:
onehotencoder = OneHotEncoder(categorical_features= [0])
X = onehotencoder.fit_transform(X).toarray()

In [10]:
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 4.8e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.8e+01, 6.1e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 4.0e+01, 6.1e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.5e+01, 5.8e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.8e+01, 5.2e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.8e+01, 7.9e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04]])

In [11]:
#for y onehotencoder won't be needed as we will label it with labelencoder.
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [12]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [13]:
#Now as we can see that Salary is in a different scaling with age, and as most of the ML algorithms depend on
#euclidean distances so here Salary will dominate Age.
#So we will scale them to same range.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

#### Two types of feature scaling:
* Standardisation : x_stand = (x - mean(x)) / std(x)
* Normalisation : x_norm = (x - xmin) / (xmax - xmin)

In [14]:
X #compare it to above

array([[ 1.22474487, -0.65465367, -0.65465367,  0.76973439,  0.77256767],
       [-0.81649658, -0.65465367,  1.52752523, -1.69922498, -1.40879986],
       [-0.81649658,  1.52752523, -0.65465367, -1.26352627, -0.86345798],
       [-0.81649658, -0.65465367,  1.52752523, -0.10166303, -0.22722578],
       [-0.81649658,  1.52752523, -0.65465367,  0.18880278, -0.22722578],
       [ 1.22474487, -0.65465367, -0.65465367, -0.53736175, -0.49989673],
       [-0.81649658, -0.65465367,  1.52752523, -0.10166303, -1.04523861],
       [ 1.22474487, -0.65465367, -0.65465367,  1.35066601,  1.40879986],
       [-0.81649658,  1.52752523, -0.65465367,  1.64113182,  1.77236112],
       [ 1.22474487, -0.65465367, -0.65465367, -0.24689594,  0.3181161 ]])

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=0)

#### We have our processed data ready!